version: '3.8'
services:
  backend:
    build: ./DashyBuilder.Backend
    ports:
      - "5000:5000"
    volumes:
      - ./DashyBuilder.Backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./DashyBuilder.Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./DashyBuilder.Frontend:/app
    environment:
      - NODE_ENV=production
